name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore csharp.sln

    - name: Build solution
      run: msbuild csharp.sln -t:rebuild -property:Configuration=Release

    - name: Run UnitTests
      run: packages/NUnit.ConsoleRunner.3.15.2/tools/nunit3-console.exe  bin/Debug/csharp.dll
